nginx:
  container_name: nginx
  image: nginx
  ports: 
    - "80:80"
    - "443:443"
  volumes:
    - ./www:/var/www/html 
    - ./nginx/etc/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/log:/var/log/nginx
  links:
    - php-fpm
php-fpm:
  container_name: php-fpm
  image: lojzik/php-fpm
  volumes:
    - ./www:/var/www/html
    - ./php/log:/var/log
  links:
    - mariadb
mariadb:
  container_name: mariadb
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=heslo       
  volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/log:/var/log/mysql
